// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Sound/SoundBase.h"
#include "Particles/ParticleSystem.h"
#include "Particles/ParticleSystemComponent.h" 
#include "Projectile.generated.h"


UCLASS()
class COW_3RDPERSON_API AProjectile : public AActor
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	AProjectile();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;

private:

	UPROPERTY(EditDefaultsOnly, Category = "Combat")
	UStaticMeshComponent* ProjectileMesh;

	UPROPERTY(VisibleAnywhere, Category = "Movement")
	UProjectileMovementComponent* ProjectileMovementComponent;

	UPROPERTY(EditAnywhere)
	float Damage = 50.f;

	UFUNCTION()
	void OnHit(
		UPrimitiveComponent* HitComp, //Component that hit something
		AActor* OtherActor, //Actor that got hit
		UPrimitiveComponent* OtherComp, //Component associated to the actor that got hit
		FVector NormalImpulse, //Impact generated by the hit
		const FHitResult& Hit //Variable that will store info about the hit results
	);

	// particle syst var
	UPROPERTY(EditAnywhere, Category = "Combat")
	UParticleSystem* HitParticles;

	// particle system component
	UPROPERTY(EditAnywhere, Category = "Combat")
	UParticleSystemComponent* TrailParticles;

	UPROPERTY(EditAnywhere, Category = "Combat")
	USoundBase* HitSound; 

	UPROPERTY(EditAnywhere, Category = "Combat")
	USoundBase* LaunchSound; 

};
